// ============================================================================
// Seed data. PRODUCTION ships EMPTY — items and launch plans are created by
// the coordinators through the UI. Set NEXT_PUBLIC_DEMO_DATA=1 at build time
// to load a rich mock portfolio (for management demos / walkthroughs only).
// NEXT_PUBLIC_DEMO_MODE only controls the role-switcher tabs, not the data.
// Bump SEED_V in domain.ts to force local storage to reseed.
// ============================================================================
import type { Item } from './domain';
import type { LaunchPlan } from './domain';

export const DEMO_DATA = process.env.NEXT_PUBLIC_DEMO_DATA === '1';
// Server-side opt-in for the DB seed (prisma/seed.ts): loads the sample
// portfolio into a demo/staging database. Never set in production.
const demoSeedOn = () => DEMO_DATA || process.env.SEED_DEMO_ITEMS === '1';

const T = (s: string) => Date.parse(s); // fixed, deterministic timestamps

export function seedItems(): Item[] {
  if (!demoSeedOn()) return [];
  return demoItems();
}

export function seedLaunchPlans(): LaunchPlan[] {
  if (!demoSeedOn()) return [];
  return demoLaunchPlans();
}

function demoItems(): Item[] {
  return [
    // ── مسودة (منسق المسار يكملها ويرسلها) ─────────────────────────────
    {
      id: 'm1',
      wf: 'draft',
      type: 'project',
      title: 'مساعد ذكي للمراسلات الداخلية',
      desc: 'مساعد لغوي لصياغة وتلخيص المراسلات الداخلية وتصنيفها آلياً.',
      path: 'strategy',
      approval: 'مسودة',
      status: 'لم يبدأ بعد',
      priority: 'متوسطة',
      rank: 2,
      complexity: 'متوسط',
      impact: 'متوسط',
      transformability: 'قابل جزئياً',
      readiness: 'الجاهزية للتحول بنسبة بين 50% إلى 80%',
      usageIntensity: 'متوسطة',
      transformPriority: 'متوسطة',
      automationPct: 10,
      progress: 0,
      expectedOutputs: 'مساعد صياغة، لوحة تصنيف',
      expectedOutcomes: 'خفض زمن إعداد المراسلات بنسبة 40%.',
      aiModels: 1,
      targetPct: 40,
      endDate: '2027-02-15',
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // ── مسودة مُعادة بملاحظات ممثل الجهة (بحاجة إلى تعديل) ─────────────
    {
      id: 'm2',
      wf: 'draft',
      type: 'operation',
      title: 'أتمتة تدقيق طلبات الموارد البشرية',
      desc: 'تدقيق آلي لطلبات الإجازات والبدلات مع التحقق من السياسات.',
      ret: {
        type: 'info',
        from: 'ممثل الجهة',
        note: 'يرجى تحديد الأنظمة المرتبطة وحجم الطلبات الشهري قبل إعادة الإرسال.',
        gate: 'priority',
      },
      path: 'ops',
      approval: 'بحاجة إلى تحديث',
      priority: 'عالية',
      rank: 1,
      complexity: 'منخفض',
      impact: 'متوسط',
      opType: 'عمليات الدعم المؤسسي',
      subActivities: 'استلام، تدقيق، اعتماد',
      sector: 'الإداري',
      dept: 'إدارة الموارد البشرية',
      section: 'قسم الخدمات الذاتية',
      automationLevel: 'جزئياً',
      automationPct: 30,
      automationSystem: 'نظام الموارد البشرية',
      usageIntensity: 'عالية',
      complexityLevel: 'منخفض',
      transformability: 'قابل كلياً',
      readiness: 'الجاهزية للتحول بنسبة بين 50% إلى 80%',
      transformPriority: 'عالية',
      progress: 0,
      endDate: '2026-12-15',
      steps: [],
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // ── بانتظار اعتماد ممثل الجهة ───────────────────────────────────────
    {
      id: 'm3',
      wf: 'ent1',
      type: 'operation',
      title: 'التصنيف الآلي للمعاملات الواردة',
      desc: 'تصنيف وتوجيه المعاملات الواردة باستخدام معالجة اللغة الطبيعية.',
      path: 'ops',
      approval: 'تم الإرسال',
      priority: 'عالية',
      rank: 1,
      complexity: 'متوسط',
      impact: 'مرتفع',
      opType: 'العمليات التخصصية',
      subActivities: 'استلام، تصنيف، توجيه',
      sector: 'الخدمي',
      dept: 'إدارة الاتصال',
      section: 'قسم المعاملات',
      automationLevel: 'جزئياً',
      automationPct: 25,
      automationSystem: 'نظام المراسلات',
      usageIntensity: 'عالية',
      complexityLevel: 'متوسط',
      transformability: 'قابل كلياً',
      readiness: 'الجاهزية للتحول بنسبة 80% فأكثر',
      transformPriority: 'عالية',
      progress: 0,
      scopeOfWork: 'بناء نموذج تصنيف عربي وربطه بنظام المراسلات مع مسار مراجعة بشرية للاستثناءات.',
      budget: '750,000 درهم',
      execBatch: 'إطلاق المرحلة الأولى',
      launchPlanIds: ['lp2'],
      endDate: '2026-11-30',
      steps: [],
      phases: [],
      launches: [
        {
          title: 'تفعيل التصنيف الآلي للمعاملات',
          ltype: 'إعلان رسمي',
          date: '2026-11-20',
          desc: '',
          status: 'مخطط',
          done: false,
        },
      ],
      execChecklist: [
        { key: 'agents', label: 'بناء النظام الوكيلي', status: 'لم تبدأ', newDate: '', reason: '' },
        { key: 'testing', label: 'الاختبار وضمان الجودة', status: 'لم تبدأ', newDate: '', reason: '' },
        { key: 'pilot', label: 'الإطلاق', status: 'لم تبدأ', newDate: '', reason: '' },
      ],
      links: [],
    },

    // ── قيد التنفيذ (معتمد، قابل للترشيح/التمويل) ──────────────────────
    {
      id: 'm4',
      wf: 'exec',
      type: 'project',
      title: 'منصة الخدمات الاستباقية',
      desc: 'تقديم الخدمات الحكومية استباقياً بناءً على أحداث حياة المتعامل.',
      path: 'services',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      priority: 'عالية',
      rank: 1,
      complexity: 'عالٍ',
      impact: 'مرتفع',
      transformability: 'قابل كلياً',
      readiness: 'الجاهزية للتحول بنسبة 80% فأكثر',
      usageIntensity: 'عالية',
      transformPriority: 'عالية',
      automationPct: 20,
      progress: 35,
      expectedOutputs: 'منصة استباقية، محرك أحداث',
      expectedOutcomes: 'تقديم 15 خدمة استباقياً دون طلب من المتعامل.',
      expectedImpact: 'رفع رضا المتعاملين إلى 95%',
      aiModels: 3,
      targetPct: 70,
      endDate: '2026-12-20',
      nom: {
        by: 'معالي مريم بنت أحمد الحمادي',
        role: 'رئيس المسار',
        path: 'services',
        at: T('2026-06-27T10:00:00'),
      },
      scopeOfWork: 'بناء محرك أحداث الحياة وتكامله مع 5 أنظمة خدمية، مع مساعد ذكي للمتعاملين.',
      budget: '2,400,000 درهم',
      execBatch: 'إطلاق المرحلة الأولى',
      launchPlanIds: ['lp1'],
      phases: [],
      launches: [
        {
          title: 'إطلاق الخدمات الاستباقية',
          ltype: 'إطلاق منتج / خدمة',
          date: '2026-11-25',
          desc: 'إطلاق المرحلة الأولى من الخدمات الاستباقية للجمهور.',
          status: 'مخطط',
          done: false,
        },
      ],
      execChecklist: [
        { key: 'agents', label: 'بناء النظام الوكيلي', status: 'مكتمل', newDate: '', reason: '' },
        { key: 'testing', label: 'الاختبار وضمان الجودة', status: 'لم تبدأ', newDate: '', reason: '' },
        { key: 'pilot', label: 'الإطلاق', status: 'لم تبدأ', newDate: '', reason: '' },
      ],
      links: [],
    },

    // ── قيد التنفيذ لدى جهة أخرى + إطلاق مشترك مع m4 ────────────────────
    {
      id: 'm5',
      wf: 'exec',
      type: 'service',
      title: 'خدمة تجديد الرخص التجارية الذكية',
      desc: 'تجديد فوري للرخص التجارية عبر مساعد محادثة ذكي.',
      path: 'services',
      entity: 'وزارة الاقتصاد والسياحة',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      priority: 'عالية',
      rank: 2,
      complexity: 'متوسط',
      impact: 'مرتفع',
      serviceOwner: 'إدارة التسجيل التجاري',
      targetUsers: 'قطاع الأعمال',
      currentJourney: 'تقديم الطلب، مراجعة يدوية، الدفع، الإصدار',
      painPoints: 'تعدد الخطوات وطول زمن المراجعة',
      expectedImprovement: 'تجديد فوري خلال دقائق دون تدخل يدوي',
      transformability: 'قابل كلياً',
      readiness: 'الجاهزية للتحول بنسبة 80% فأكثر',
      usageIntensity: 'عالية',
      transformPriority: 'عالية',
      automationLevel: 'جزئياً',
      automationPct: 55,
      progress: 45,
      budget: '1,100,000 درهم',
      scopeOfWork: 'بناء مساعد محادثة للتجديد مع التكامل مع بوابة الدفع والسجل التجاري.',
      execBatch: 'إطلاق المرحلة الأولى',
      launchPlanIds: ['lp1'],
      endDate: '2026-11-30',
      phases: [],
      launches: [
        {
          title: 'إطلاق الخدمات الاستباقية',
          ltype: 'إطلاق منتج / خدمة',
          date: '2026-11-25',
          desc: 'إطلاق المرحلة الأولى من الخدمات الاستباقية للجمهور.',
          status: 'مخطط',
          done: false,
          shared: true,
        },
      ],
      execChecklist: [
        { key: 'agents', label: 'بناء النظام الوكيلي', status: 'مكتمل', newDate: '', reason: '' },
        { key: 'testing', label: 'الاختبار وضمان الجودة', status: 'لم تبدأ', newDate: '', reason: '' },
        { key: 'pilot', label: 'الإطلاق', status: 'لم تبدأ', newDate: '', reason: '' },
      ],
      links: [],
    },

    // ── قيد التنفيذ لدى جهة ثالثة (مسار بناء القدرات) ───────────────────
    {
      id: 'm6',
      wf: 'exec',
      type: 'initiative',
      title: 'برنامج سفراء الذكاء الاصطناعي',
      desc: 'تأهيل 100 موظف كسفراء للتحول الذكي داخل الوزارة.',
      path: 'capacity',
      entity: 'وزارة الصحة ووقاية المجتمع',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      priority: 'متوسطة',
      rank: 1,
      complexity: 'منخفض',
      impact: 'متوسط',
      transformability: 'قابل جزئياً',
      readiness: 'الجاهزية للتحول بنسبة بين 50% إلى 80%',
      usageIntensity: 'متوسطة',
      transformPriority: 'متوسطة',
      automationPct: 0,
      progress: 25,
      expectedOutputs: 'منهج تدريبي، 100 سفير معتمد',
      expectedOutcomes: 'نشر ثقافة التحول الذكي في جميع الإدارات.',
      aiModels: 0,
      targetPct: 30,
      endDate: '2027-01-31',
      budget: '900,000 درهم',
      nom: {
        by: 'اللجنة الوطنية',
        role: 'اللجنة الوطنية',
        path: 'capacity',
        at: T('2026-06-28T11:30:00'),
        direct: true,
      },
      scopeOfWork: 'تصميم المنهج وتنفيذ 6 دفعات تدريبية مع شهادات معتمدة.',
      execBatch: 'إطلاق المرحلة الثانية',
      launchPlanIds: ['lp4'],
      phases: [],
      launches: [
        {
          title: 'حفل تخريج سفراء الذكاء الاصطناعي',
          ltype: 'مؤتمر / فعالية',
          date: '2027-01-20',
          desc: 'تخريج المرحلة الأولى من السفراء المعتمدين.',
          status: 'مخطط',
          done: false,
        },
      ],
      execChecklist: [
        { key: 'agents', label: 'بناء النظام الوكيلي', status: 'مكتمل', newDate: '', reason: '' },
        { key: 'testing', label: 'الاختبار وضمان الجودة', status: 'مكتمل', newDate: '', reason: '' },
        { key: 'pilot', label: 'الإطلاق', status: 'لم تبدأ', newDate: '', reason: '' },
      ],
      links: [],
    },

    // ── قيد الإطلاق (بنود التنفيذ مكتملة، الإطلاق متبقٍ) ────────────────
    {
      id: 'm7',
      wf: 'launch',
      type: 'project',
      title: 'محرك التوصيات للبيانات الحكومية',
      desc: 'محرك توصيات يقترح مجموعات بيانات وتقارير حسب دور المستخدم.',
      path: 'tech',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      priority: 'عالية',
      rank: 1,
      complexity: 'عالٍ',
      impact: 'مرتفع',
      transformability: 'قابل كلياً',
      readiness: 'الجاهزية للتحول بنسبة 80% فأكثر',
      usageIntensity: 'عالية',
      transformPriority: 'عالية',
      automationPct: 40,
      progress: 85,
      expectedOutputs: 'محرك توصيات + واجهات برمجية',
      expectedOutcomes: 'رفع استخدام البيانات المفتوحة بنسبة 60%.',
      aiModels: 2,
      targetPct: 65,
      endDate: '2026-10-15',
      budget: '3,200,000 درهم',
      nom: {
        by: 'سعادة عمر سلطان العلماء',
        role: 'رئيس المسار',
        path: 'tech',
        at: T('2026-06-26T09:15:00'),
      },
      scopeOfWork: 'بناء محرك التوصيات وتكامله مع منصة البيانات الوطنية.',
      execBatch: 'إطلاق المرحلة الأولى',
      launchPlanIds: ['lp3'],
      phases: [],
      launches: [
        {
          title: 'تفعيل محرك التوصيات',
          ltype: 'إعلان رسمي',
          date: '2026-10-10',
          desc: 'تفعيل التوصيات لمستخدمي منصة البيانات.',
          status: 'قيد الإعداد',
          done: false,
        },
      ],
      execChecklist: [
        { key: 'agents', label: 'بناء النظام الوكيلي', status: 'مكتمل', newDate: '', reason: '' },
        { key: 'testing', label: 'الاختبار وضمان الجودة', status: 'مكتمل', newDate: '', reason: '' },
        { key: 'pilot', label: 'الإطلاق', status: 'مكتمل', newDate: '', reason: '' },
      ],
      links: [],
    },

    // ── مكتمل + مموّل من اللجنة (يُظهر المصروف والسلة المعتمدة) ─────────
    {
      id: 'm8',
      wf: 'done',
      type: 'service',
      title: 'خدمة الاستعلام الذكي الموحّد',
      desc: 'مساعد محادثة موحّد للاستعلام عن حالة الطلبات عبر القنوات.',
      path: 'services',
      approval: 'معتمد',
      status: 'مكتمل',
      priority: 'عالية',
      rank: 1,
      complexity: 'متوسط',
      impact: 'مرتفع',
      serviceOwner: 'إدارة خدمة المتعاملين',
      targetUsers: 'الأفراد والمؤسسات',
      currentJourney: 'اتصال هاتفي أو زيارة للاستعلام',
      painPoints: 'ضغط على مركز الاتصال وتكرار الاستفسارات',
      expectedImprovement: 'إجابة فورية آلية بنسبة 80% من الاستفسارات',
      transformability: 'قابل كلياً',
      readiness: 'الجاهزية للتحول بنسبة 80% فأكثر',
      usageIntensity: 'عالية',
      transformPriority: 'عالية',
      automationLevel: 'كلياً',
      automationPct: 90,
      progress: 100,
      budget: '1,500,000 درهم',
      scopeOfWork: 'بناء المساعد الموحّد وربطه بأنظمة الطلبات عبر القنوات الرقمية.',
      execBatch: 'إطلاق المرحلة الأولى',
      launchPlanIds: ['lp5'],
      endDate: '2026-09-15',
      nom: {
        by: 'سعادة محمد راشد بن طليعة',
        role: 'رئيس المسار',
        path: 'services',
        at: T('2026-06-20T09:00:00'),
      },
      funded: { by: 'اللجنة الوطنية', at: T('2026-06-25T13:30:00'), direct: false },
      phases: [],
      launches: [
        {
          title: 'إطلاق الاستعلام الذكي',
          ltype: 'إطلاق منتج / خدمة',
          date: '2026-09-10',
          desc: '',
          status: 'تم الإطلاق',
          done: true,
          doneAt: T('2026-09-10T10:00:00'),
        },
      ],
      execChecklist: [
        { key: 'agents', label: 'بناء النظام الوكيلي', status: 'مكتمل', newDate: '', reason: '' },
        { key: 'testing', label: 'الاختبار وضمان الجودة', status: 'مكتمل', newDate: '', reason: '' },
        { key: 'pilot', label: 'الإطلاق', status: 'مكتمل', newDate: '', reason: '' },
      ],
      links: [],
    },

    // ── عملية قيد التنفيذ في مسار العمليات (تظهر لرئيس المسار) ──────────
    {
      id: 'm9',
      wf: 'exec',
      type: 'operation',
      title: 'أتمتة معالجة طلبات الدعم الفني',
      desc: 'استقبال وتشخيص وتوجيه طلبات الدعم الفني آلياً عبر وكيل ذكي.',
      path: 'ops',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      priority: 'عالية',
      rank: 2,
      complexity: 'متوسط',
      impact: 'مرتفع',
      opType: 'العمليات المساندة',
      subActivities: 'استلام، تشخيص، حل، تصعيد',
      sector: 'الخدمي',
      dept: 'إدارة تقنية المعلومات',
      section: 'قسم الدعم الفني',
      automationLevel: 'جزئياً',
      automationPct: 35,
      automationSystem: 'نظام إدارة التذاكر',
      usageIntensity: 'عالية',
      complexityLevel: 'متوسط',
      transformability: 'قابل كلياً',
      readiness: 'الجاهزية للتحول بنسبة 80% فأكثر',
      transformPriority: 'عالية',
      targetPct: 60,
      progress: 40,
      scopeOfWork: 'بناء وكيل ذكي لتشخيص طلبات الدعم وربطه بنظام التذاكر مع تصعيد بشري للحالات المعقدة.',
      budget: '900,000 درهم',
      execBatch: 'إطلاق المرحلة الأولى',
      launchPlanIds: ['lp2'],
      endDate: '2026-11-30',
      steps: [],
      phases: [],
      launches: [
        {
          title: 'تفعيل التصنيف الآلي للمعاملات',
          ltype: 'إعلان رسمي',
          date: '2026-11-20',
          desc: '',
          shared: true,
          status: 'مخطط',
          done: false,
        },
      ],
      execChecklist: [
        { key: 'agents', label: 'بناء النظام الوكيلي', status: 'قيد التنفيذ', newDate: '', reason: '' },
        { key: 'testing', label: 'الاختبار وضمان الجودة', status: 'لم تبدأ', newDate: '', reason: '' },
        { key: 'pilot', label: 'الإطلاق', status: 'لم تبدأ', newDate: '', reason: '' },
      ],
      links: [],
    },
  ];
}

function demoLaunchPlans(): LaunchPlan[] {
  return [
    {
      id: 'lp1',
      batch: 'إطلاق المرحلة الأولى',
      title: 'إطلاق الخدمات الاستباقية',
      ltype: 'إطلاق منتج / خدمة',
      date: '2026-11-25',
      desc: 'إطلاق المرحلة الأولى من الخدمات الاستباقية للجمهور.',
      scope: 'تحويل مجموعة الخدمات الاستباقية الأولى وربطها بمحرك أحداث الحياة.',
      budget: '3,500,000 درهم',
      launchBudget: '450,000 درهم',
    },
    {
      id: 'lp2',
      batch: 'إطلاق المرحلة الأولى',
      title: 'تفعيل التصنيف الآلي للمعاملات',
      ltype: 'إعلان رسمي',
      date: '2026-11-20',
      desc: '',
      scope: 'أتمتة مجموعة عمليات المعاملات والدعم الفني التي تُطلق معاً.',
      budget: '1,650,000 درهم',
      launchBudget: '150,000 درهم',
    },
    {
      id: 'lp3',
      batch: 'إطلاق المرحلة الأولى',
      title: 'تفعيل محرك التوصيات',
      ltype: 'إعلان رسمي',
      date: '2026-10-10',
      desc: 'تفعيل التوصيات لمستخدمي منصة البيانات.',
      scope: 'تفعيل محرك التوصيات على بيانات المنصة الحكومية.',
      budget: '800,000 درهم',
      launchBudget: '80,000 درهم',
    },
    {
      id: 'lp4',
      batch: 'إطلاق المرحلة الثانية',
      title: 'حفل تخريج سفراء الذكاء الاصطناعي',
      ltype: 'مؤتمر / فعالية',
      date: '2027-01-20',
      desc: 'تخريج المرحلة الأولى من السفراء المعتمدين.',
      scope: 'تأهيل وتخريج دفعة سفراء الذكاء الاصطناعي.',
      budget: '600,000 درهم',
      launchBudget: '350,000 درهم',
    },
    {
      id: 'lp5',
      batch: 'إطلاق المرحلة الأولى',
      title: 'إطلاق الاستعلام الذكي',
      ltype: 'إطلاق منتج / خدمة',
      date: '2026-09-10',
      desc: '',
      scope: 'إطلاق مساعد الاستعلام الموحّد عبر القنوات.',
      budget: '1,500,000 درهم',
      launchBudget: '120,000 درهم',
    },
  ];
}
